-   id: go-build
    name: go build check
    entry: go-build
    language: golang
    description: Runs go build, requires golang
-   id: go-test
    name: go test check
    entry: go-test
    language: golang
    description: Runs go testing, requires golang
-   id: go-errcheck
    name: go error check
    entry: go-errcheck
    language: golang
    description: Runs error checker, requires golang
-   id: go-goimports
    name: goimports check
    entry: go-goimports
    language: golang
    description: Runs goimports tool
-   id: go-imports
    name: imports check
    entry: go-imports
    language: golang
    description: Runs own imports tool implementation
-   id: go-vet
    name: go vet check
    entry: go-vet
    language: golang
    description: Runs own go vet tool implementation
-   id: dockercheck
    name: dockerheck
    entry: dockercheck
    language: golang
    description: Runs Dockfile checking tool, requires golang
-   id: composecheck
    name: composecheck
    entry: composecheck
    language: golang
    description: Checks docker-compose.yml files